apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DOCKER_IMAGE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DOCKER_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${DOCKER_IMAGE_NAME}
    spec:
      containers:
      - name: ${DOCKER_IMAGE_NAME}
        image: ${ACR_NAME}/${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
        ports:
        - containerPort: 80
        
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
          limits:
            cpu: 100m
            memory: 700Mi           
      
---
apiVersion: v1
kind: Service
metadata:
  name: ${DOCKER_IMAGE_NAME}
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ${DOCKER_IMAGE_NAME}