subscription_id     = "${SUBSCRIPTION_ID}"
client_id           = "${CLIENT_ID}"
client_secret       = "${CLIENT_SECRET}"
tenant_id           = "${TENANT_ID}"
location            = "${INFRASTR_LOCATION}"
resource_group_name = "${RSCE_GROUP_NAME}"
arcname             = "${ACR_NAME}"